### ISSUE TITLE
update for my_robot_description read me

### ISSUE THREAD

**Issue by Ktysai** [eborghi10/my_ROS_mobile_robot#11]
$ roscd my_robot_description/urdf/
$ rosrun xacro xacro --inorder my_robot.xacro > my_robot.urdf

For ros noetic/melodic "--inorder" is default option
$ roscd my_robot_description/urdf/
$ rosrun xacro xacro my_robot.xacro > my_robot.urdf 

also

$ urdf_to_graphviz my_robot.urdf
should be change to
$ urdf_to_graphiz my_robot.urdf

**Comment by eborghi10** [comment]
Thanks for reporting this issue, @Ktysai.

**Comment by Ktysai** [comment]
@eborghi10 I've seen some more issues with the package and ros noetic. What it will be the best, to post issues and the solution each time or can I modify them directly?

**Comment by eborghi10** [comment]
@Ktysai Create a PR and I'll review it, please. I don't have a lot of time to look at them quickly.
