### ISSUE TITLE
my_robot_navigation fatal error: move_base_msgs/MoveBaseAction.h

### ISSUE THREAD

**Issue by Ktysai** [eborghi10/my_ROS_mobile_robot#5]
Hello Emiliano,

Amazing job, for sure I'll get for more info here. Can I give 3 starts here :))

On Ubuntu 16, kinetic full install there was a problem for my_robot_navigation, when I've done
`catkin_make`

This library was needed:

`sudo apt-get install -y libmove-base-msgs-dev`

Ciao and keep up the super job!

**Comment by eborghi10** [comment]
Thanks for your feedback, @Ktysai !

Did you try running `rosdep install --from-path src -yi` before running `catkin_make`? I guess it will install it automatically.

**Comment by Ktysai** [comment]
Hello Emiliano,

No, unfortunately! It was in the read me?

Something not related to this:
I'm using several examples to make a robot do the SLAM.

I've discovered your work yesterday night  :) And it's the most human approach regarding ros_contol. A way more advanced the to do the job.
For questions regarding the URDF and the hardware which approach should be best?

BTW, thanks for the detailed readme!

All the best!

**Comment by eborghi10** [comment]
If it's not in the README, go ahead and create a PR :)

Sorry, but I didn't understand your question about URDF and hardware. What are you trying to do?

**Comment by Ktysai** [comment]
Hello Emiliano,

Regarding my_robot_description the XARCO file describes the wheels separate from chassis, LIDAR and so on (my_robot.xacro). You've done it so because there was two identical instances?
I mean everything was neat and carefully arranged and only those two were different.

I'm trying to build a differential drive robot with and Rpi 3vB as master, that has connected RPlidar and Arduino Mega 2650. The Arduino controls the driver motor and reads encoders. Any suggestions about doing the hardware interface for ROS_CONTROL?

I've used the old approach with topic and publishers, but not now luck with SLAM until now. 


All the best!
 

![Schema bloc robot](https://user-images.githubusercontent.com/8057156/63656323-ffae1300-c79a-11e9-9063-860a822c863d.jpg)

**Comment by eborghi10** [comment]
What exactly do you need to know about `ros_control`? I made an approach, using it [here](https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_base/include/my_robot_hw_interface.h).

Regarding the LiDAR, I recommend you to use [this node](http://wiki.ros.org/rplidar_ros). It should work out of the box if the power source is correct.

**Comment by Ktysai** [comment]
Thank you, Emiliano!

Indeed the RPLIDAR node works fine. It needs some tweaks since is very sensitive to some packages.

ros_control gives an interesting general approach to control a robot, only that is a little bit hard to understand. I want to learn it by implementing on a differential drive robot.

In your HW interface I still cannot see crearly the connection between  Arduino and interface.
In **DCMotorWithEncoder.h**, can be seen something, but no matching publishes
`, sub(position == LEFT ? "my_robot/left_wheel_vel" : "my_robot/right_wheel_vel", &DCMotorWithEncoder::motorCb, this)`


Btw, for robot navigation the command `rosrun my_robot_navigation send_goal <x y w>`

What are some workable coordinates?

Cheers!

**Comment by eborghi10** [comment]
If you want to learn something theoretically abou `ros_control`, read [the official Wiki](https://github.com/ros-controls/ros_control/wiki). It's very comprehensive.

I can't understand your doubt with the subscriber. Where's that line in particular?

The `send_goal` node works when there is a [transformation between the robot and the map](https://github.com/eborghi10/my_ROS_mobile_robot/blob/e04acfd3e7eb4584ba0aab8a969a74d6c30eed34/my_robot_navigation/src/send_robot_goal.cpp#L22). Do you have that? And also, you need to have `move_base` working too.

**Comment by Ktysai** [comment]
Hello Emiliano,

The line is from here:
https://github.com/eborghi10/my_ROS_mobile_robot/blob/master/my_robot_scripts/arduino_scripts/arduino_peripherals/src/arduino_peripherals/include/DCMotorWithEncoder.h

**line 26**

I was under the impression that ros_control does not use publishers/subscribers to access hardware.
It means that in your HW interface you've used pubs/subs and ros_control use the HW interface without problems?

For the `rosrun my_robot_navigation send_goal <x y w>
1, 1, 0.1 is ok to input these coordinates? It seems that on z I have to put at least 0.1 in order to move              the robot 

`


Cheers!

**Comment by eborghi10** [comment]
If you [search through the repository](https://github.com/eborghi10/my_ROS_mobile_robot/search?q=left_wheel_vel&unscoped_q=left_wheel_vel) one of those topics, you'll see that Arduino is subscribing to those topics (velocities) and the HW interface is publishing to them.

**Comment by eborghi10** [comment]
The main issue of this ticket was fixed on #10.
