### ISSUE TITLE
How do you build the urdf file?

### ISSUE THREAD

**Issue by QuangGB** [eborghi10/my_ROS_mobile_robot#9]
I want to build a robot that similar to your model. First I drawn it on Inventor and using Freecad to convert to .dae file, and I write urdf file, but it's not the same as the description. How did you do it? Can you share me some experience? Thank  for reading.

**Comment by eborghi10** [comment]
Hi @QuangGB, I recommend you to go through these tutorials first: [http://wiki.ros.org/urdf/Tutorials](http://wiki.ros.org/urdf/Tutorials)

**Comment by QuangGB** [comment]
Thank you so much. I am implementing a project that is similar to your
project. I hope I can learn from you.


Vào Th 2, 18 thg 1, 2021 vào lúc 18:11 Emiliano Borghi <
notifications@github.com> đã viết:
